
services:
  serverplus:
    build: .
    container_name: serverplus
    ports:
      - "8000:8000"
    volumes:
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=local
      - DB_CONNECTION=sqlite
    stdin_open: true
    tty: true
